name: publications

services:
  # Build static site
  mkdocs:
    container_name: pub-mkdocs
    restart: no
    build:
      context: .
      dockerfile: mkdocs/Dockerfile
    command:
      - /bin/bash
      - -c
      - |
        mkdocs build
    working_dir: /var/www
    volumes:
      - ./:/var/www
  # Run server
  nginx:
    container_name: pub-nginx
    depends_on:
      - node
    build:
      context: .
      dockerfile: nginx/Dockerfile
    restart: always
    tty: true
    ports:
      - ${PORT_WEBSITE}:3000
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf